config/routes.rb
Rails.application.routes.draw do
  resources :daily_workouts, only: [:new, :create] do
  end

  root to: "home#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_workout.rb
class DailyWorkout < ApplicationRecord
  has_many :lifts
  accepts_nested_attributes_for :lifts

  validates :focus, presence: true
end

app/models/lift.rb
class Lift < ApplicationRecord
  belongs_to :daily_workout

  lifts_attributes = %i[name sets reps]
  lifts_attributes.each do |attribute|
    validates attribute, presence: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_workouts_controller.rb
class DailyWorkoutsController < ApplicationController
  def new
    @dailyWorkout = DailyWorkout.new
    @dailyWorkout.lifts.build
  end

  def create
    @dailyWorkout = DailyWorkout.create(daily_workout_params)
    if @dailyWorkout.save
      flash[:success] = "New Daily_Workout created successfuly!"
      redirect_to root_path
    else
      # flash[:error] = "Something went wrong"
      render :new
    end
  end

  private

  def daily_workout_params
    # params.require(:daily_workout).permit(:focus, lifts_attributes: %i[name sets reps])
    params.require(:daily_workout).permit(:focus, lifts_attributes: [:name, :sets, :reps])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @daily_workout = DailyWorkout.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_workouts_helper.rb
module DailyWorkoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/daily_workouts/_daily_workout.html.erb
<div class='flex flex-col justify-center items-center w-full h-auto text-gray-800'>
    <section class='flex flex-col justify-center items-center space-y-6 px-3 w-full h-auto'>
        <div class='w-full flex flex-col items-center justify-center gap-2'>
            <span class='block uppercase text-indigo-600 font-medium text-[20px]'>today's program</span>
            <h2 class='text-center text-4xl font-bold tracking-tight text-gray-800'>Shape your physique through a determined state of mind and Explosive power.</h2>
        </div>
        <div class='w-full py-5'>
            <div class="flex flex-col w-full">
            <div class="overflow-x-auto">
                <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="w-full text-center border-collapse border border-gray-800 capitalize">
                        <thead class='bg-gray-200'>
                            <tr>
                                <th scope="col" class="border border-gray-800 font-medium text-gray-800 px-6 py-4">
                                    LIFT
                                </th>                                
                                <th scope="col" class="border border-gray-800 font-medium text-gray-800 px-6 py-4">
                                    SETS
                                </th>
                                <th scope="col" class="border border-gray-800 font-medium text-gray-800 px-6 py-4">
                                    REPS
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @daily_workout.lifts.each do |lift| %>
                                <tr>
                                    <td class="border border-gray-800 text-gray-800 font-light px-6 py-4 whitespace-nowrap">
                                        <%= lift.name %>
                                    </td>
                                    <td class="border border-gray-800 text-gray-800 font-light px-6 py-4 whitespace-nowrap">
                                        <%= lift.sets %>
                                    </td>
                                    <td class="border border-gray-800 text-gray-800 font-light px-6 py-4 whitespace-nowrap">
                                        <%= lift.reps %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
            </div>
        </div>
    </section>
</div>

app/views/daily_workouts/new.html.erb
<div class='grid place-content-center min-h-[100vh] h-full bg-gray-400'>
  <div class='px-5 py-2  md:w-[500px]'>
    <h1 class='text-gray-800 text-xl font-bold text-center'>Create a new Daily Workout plan</h1>
    <%= simple_form_for @dailyWorkout, html: { class: "space-y-4 md:px-10 p-2" } do |f| %>
        <% input_items_class = "px-5 w-full bg-indigo-400 placeholder:text-slate-600 text-black outline-none border-none" %>
     <div>
        <label class="block py-2 font-medium text-[16px]" for="focus">Daily focus</label>
        <%= f.input :focus, label: false, input_html: { placeholder: "Enter your focus of the day", class: input_items_class } %>
     </div>
      <%= f.simple_fields_for :lifts do |l| %>
        <div id='fieldSetContainer' >
            <fieldset id='0' class='bg-indigo-300 p-4 mt-5'>
            <h2 class="text-[16px]">Complete lifts Bellow</h2>
            <div>
                <label class="block py-2 font-medium text-[14px]" for="name">Lift name</label>
                <%= l.input :name, label: false, input_html: { placeholder: "Name of your lift", class: "#{input_items_class} " } %>
            </div>
               <div>
                <label class="block py-2 font-medium text-[14px]" for="reps">Lift Repetitions</label>
                <%= l.input :reps, label: false, input_html: { placeholder: "Number of repetions", class: "#{input_items_class} " } %>
            </div>
               <div>
                <label class="block py-2 font-medium text-[14px]" for="sets">Lift Sets</label>
                <%= l.input :sets, label: false, input_html: { placeholder: "Number of sets", class: "#{input_items_class} " } %>
            </div>
            </fieldset>
        </div>
      <% end %>
        <%= f.button :submit, "Create Daily_Workout", class: "bg-gray-800 py-4 text-center w-full" %>
    <% end %>
      <p class='w-full text-center py-3'>or</p>
     <button class='w-full py-2 text-center text-gray-800 bg-indigo-200' id='addWorkout' onClick="addWorkout()">Add lift</button> 
    <br/>
  </div>
</div>

<script>

  const addWorkout = ()=>{
    const lastId = document.querySelector('#fieldSetContainer').lastElementChild.id;
    const newId = parseInt(lastId, 10) + 1;
    const newFieldset = document.querySelector('[id="0"]').outerHTML.replace(/0/g, newId);
    document.querySelector('#fieldSetContainer').insertAdjacentHTML('beforeend', newFieldset);
  }

</script>

app/views/home/home.html.erb
<main>
  <div class='flex flex-row flex-wrap bg-gray-200'>
      <div class='md:w-1/2 w-full h-[60vh] flex justify-start items-center'>
        <div class="mx-auto  flex flex-col space-y-4 px-6">
            <h1 class="text-4xl font-bold tracking-tight text-indigo-600 sm:text-6xl">
              <span class='text-gray-800'>Fitness</span> 
              <br/>& Mindset
            </h1>
            <p class="mt-4 text-lg leading-8 text-gray-700">Shape your physique through a determined state of mind.</p>
            <div class="flex items-center justify-start gap-x-6">
              <% button_item_class = "cursor-pointer px-5 py-2 text-base font-semibold leading-7 transition-all duration-500 easy-in-out" %>
              <% button1_item_class = "bg-indigo-200 text-gray-800 hover:text-indigo-200 hover:bg-gray-800" %>
              <% button2_item_class = "bg-gray-800 text-indigo-200 hover:text-gray-800 hover:bg-indigo-200" %>
              <%= link_to "Get Started", root_path, class: "#{button_item_class} #{button2_item_class}" %>
              <%= link_to "Join Now", root_path, class: "#{button_item_class} #{button1_item_class}" %>
            </div>
        </div>
      </div>

      <div class='md:w-1/2 w-full h-[60vh] flex justify-center items-center'>
        <%= image_tag "fitness.jpg", class: "w-full h-full object-cover", layout: "fill" %>
      </div>
  </div>
  <%= render "layouts/fitness" %>

  <% if @daily_workout %>
    <%= render "daily_workouts/daily_workout" %>
  <% end %>
</main>

app/views/layouts/_fitness.html.erb
<div class='flex flex-col justify-center items-center gap-3 p-5 w-full h-auto text-gray-800'>
    <div class='text-center space-y-4 py-3'>
        <p class='font-bold text-[25px]'> "The greatest glory in living lies not in never falling, but in rising every time we fall."</p>
        <p class='text-[20px] leading-3 font-medium'>-- Nelson Mandela -- </p>
    </div>
    <section class='flex flex-col justify-center items-center gap-4 px-3 w-full h-auto py-3'>
        <div class='w-full flex flex-col items-center justify-center gap-2'>
            <span class='block uppercase text-indigo-600 font-medium text-[20px]'>fitness</span>
            <h2 class='text-center text-4xl font-bold tracking-tight text-gray-800'>Create a Healthy Life</h2>
        </div>
        <div class='grid md:grid-cols-2 grid-cols-1 md:gap-2 gap-1 w-full items-center justify-center'>
            <div class='flex md:flex-row flex-col gap-x-3 justify-center items-start p-4 transition-all duration-300 ease-linear hover:bg-gray-200'>
                <button class="bg-indigo-600 p-2 text-white rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                </button>
                <div>
                    <h4 class='font-bold'>Online Catalog</h4>
                    <p class='text-gray-600'>
                        The greatest glory in living lies not in never falling, but in rising every time we fall," 
                        by Nelson Mandela, is a powerful message about resilience and determination. 
                        It speaks to the idea that success and fulfillment in life are not about <span class='font-medium text-indigo-600'>avoiding failure</span>. 
                    </p>
                </div>
            </div>

            <div class='flex md:flex-row flex-col gap-x-3 justify-center items-start p-4 transition-all duration-300 ease-linear hover:bg-gray-200'>
                <button class="bg-indigo-600 p-2 text-white rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v17.25m0 0c-1.472 0-2.882.265-4.185.75M12 20.25c1.472 0 2.882.265 4.185.75M18.75 4.97A48.416 48.416 0 0012 4.5c-2.291 0-4.545.16-6.75.47m13.5 0c1.01.143 2.01.317 3 .52m-3-.52l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.988 5.988 0 01-2.031.352 5.988 5.988 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L18.75 4.971zm-16.5.52c.99-.203 1.99-.377 3-.52m0 0l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.989 5.989 0 01-2.031.352 5.989 5.989 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L5.25 4.971z" />
                    </svg>
                </button>
                <div>
                    <h4 class='font-bold'>Balance your lifestyle</h4>
                    <p class='text-gray-600'>
                        The greatest glory in living lies not in never falling, but in rising every time we fall," 
                        by Nelson Mandela, is a powerful message about resilience and determination. 
                        It speaks to the idea that success and fulfillment in life are not about <span class='font-medium text-indigo-600'>avoiding failure</span>. 
                    </p>
                </div>
            </div>

            <div class='flex md:flex-row flex-col gap-x-3 justify-center items-start p-4 transition-all duration-300 ease-linear hover:bg-gray-200'>
                <button class="bg-indigo-600 p-2 text-white rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
                    </svg>
                </button>
                <div>
                    <h4 class='font-bold'>Look great and smart</h4>
                    <p class='text-gray-600'>
                        The greatest glory in living lies not in never falling, but in rising every time we fall," 
                        by Nelson Mandela, is a powerful message about resilience and determination. 
                        It speaks to the idea that success and fulfillment in life are not about <span class='font-medium text-indigo-600'>avoiding failure</span>. 
                    </p>
                </div>
            </div>

            <div class='flex md:flex-row flex-col gap-x-3 justify-center items-start p-4 transition-all duration-300 ease-linear hover:bg-gray-200'>
                <button class="bg-indigo-600 p-2 text-white rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                    </svg>
                </button>
                <div>
                    <h4 class='font-bold'>Boost your mood</h4>
                    <p class='text-gray-600'>
                        The greatest glory in living lies not in never falling, but in rising every time we fall," 
                        by Nelson Mandela, is a powerful message about resilience and determination. 
                        It speaks to the idea that success and fulfillment in life are not about <span class='font-medium text-indigo-600'>avoiding failure</span>. 
                    </p>
                </div>
            </div>
        </div>
    </section>
</div>

app/views/layouts/_nav.html.erb
<div class='bg-gray-800 text-white'>
    <nav class='flex flex-col md:flex-row gap-3 justify-between items-center md:px-20 px-5 py-5'> 
        <div>
            <%= link_to content_tag(:span, "Fitness", class: "text-indigo-400") + " & Mindset", root_path, class: "md:text-2xl text-xl cursor-pointer font-bold tracking-widest uppercase" %>
        </div>
        <div class='flex flex-col md:flex-row'>
            <% nav_item_class = "transition-all duration-500 easy-in-out mix-w-[50px] px-4 py-2 text-sm font-semibold bg-transparent hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shodow-outline" %>
            <%= link_to "Get Stared", root_path, class: nav_item_class %>
            <%= link_to "Monthly plan", "#", class: nav_item_class %>
            <%= link_to "Login", root_path, class: nav_item_class %>
            <%= link_to "Add Daily Workout", new_daily_workout_path, class: nav_item_class %>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness & Mindset</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Welcome to Fitness & Mindset, 
    where we believe that the key to a fit and healthy physique lies 
    in a determined state of mind. Our mission is to empower individuals 
    to transform their bodies and their lives through a combination of 
    physical fitness and mental strength. We understand that achieving a 
    desired physique is not just about hitting the gym or following a 
    strict diet, but it requires a deep commitment and a positive mindset. T
    hat's why our website offers a comprehensive approach to fitness, 
    including workout routines, nutrition plans, and mental wellness strategies. 
    Join us on a journey to becoming the best version of yourself, 
    both physically and mentally. Embrace the power of determination and let Fitness 
    & Mindset help you reach your fitness goals.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>    
    <main>
      <% flash.each do |message_type, message| %>
        <div id='alert' class='absolute w-full flex items-center justify-center'>
          <div class='relative md:w-[70%] w-full h-auto text-center bg-green-300 py-5'>
            <%= message %>
            <button class="absolute text-gray-800 px-4 bg-red-400 text-[20px] font-bold top-0 h-full right-0" onclick="this.parentElement.style.display='none'">
              &times;
            </button>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>

    <% # JavaScript fuction %>

    <script>
      setTimeout(function() {
        let alertElement = document.getElementById("alert");
        if (alertElement) {
          alertElement.style.display = "none";
        }
      }, 3500);
    </script>
  </body>
</html>